### ISSUE TITLE
Running the game server locally and updating .wasm files crashes the game

### ISSUE THREAD

**Issue by golddranks** [tonarino/bomberman-of-the-hill#61]
This seem to be a Bevy issue, that surfaces when you symlink an asset directory outside of the main Bevy asset directory, as it is currently set up in this repo. I reported it to Bevy: https://github.com/bevyengine/bevy/issues/5689

**Comment by bschwind** [comment]
Hey, thanks for reporting and thanks for attending the event!

We ran into similar issues with symlinks, I'll be interested to hear what the bevy devs decide on this one.

**Comment by strohel** [comment]
Unless this is quickly resolved at Bevy side, we can work-around it by symlinking from `rounds` to `.../assets/` rather than the other way around.
